MOM_file_parser unit test implementation
NOAA-GFDL/MOM6 pull request #119
Opened 2022-04-29 14:13 UTC by marshallward

This patch introduces new features to support unit testing of the MOM6
source code.  The patch includes two new modules (MOM_unit_testing,
MOM_file_parser_tests), two new classes (UnitTest, TestSuite), and a new
driver (unit_testing).

A UnitTest object consists of the following:

* The test subroutine
* Test name (for reporting)
* A flag indicating whether the test should fail (FATAL)
* An optional cleanup subroutine

The UnitTest objects are gathered into a TestSuite object, which
provides a batch job for running all of its tests.

The use of these features is demonstrated in a driver, unit_tests, which
runs the tests provided in the MOM_file_parser_tests module

This patch also includes changes to the ".testing" build system.

* The optional FCFLAGS_COVERAGE has been removed from the testing
  Makefile.  Instead, a new "cov" target is optionally built if one
  wants to check the coverage.  It is currently based on "symmetric".

* A new "unit" target has been added to run the unit testing driver and
  report its code coverage.

* GitHub Actions has been modified to include the unit driver test.

* The gcov output now includes branching (-b), which allows reporting of
  partial line coverage in some cases.

* codecov.io "smart" report searching has been replaced with an explicit
  setting of the root directory (-R) and *.gcda paths.

Other minor changes:

* MOM_coms include an infra-level sync function (sync_PEs) as a wrapper
  to mpp_sync (or others in the future).

2022-05-10 14:03 UTC, marshallward commented on src/framework/MOM_unit_testing.F90
> +implicit none
I don't understand, I am using `private` already.

2022-05-16 18:18 UTC, marshallward commented on src/framework/MOM_unit_testing.F90
> +implicit none
I have added the Hallberg semicolons.

2022-05-16 18:54 UTC, Hallberg-NOAA approved these changes
I have examined these changes, and despite not being fluent in the syntax of .yml, .ac, or Makefiles, all of the changes here seem sensible.  I will trigger the pipeline testing of these changes after this PR comes to the top of the queue, and after updating the base branch.

2022-05-20 09:07 UTC, Hallberg-NOAA commented
The PGI build step in the pipeline is failing, apparently at lines 761 and 780 of MOM_file_parser_tests.F90.  I have tried this 3 times, with the same result each time.  It appears that the pgi compiler is interpreting the " /'" construct as an escape on the closing quote, leading to the erroneous error messages about mismatched quotes., @marshallward, please see what needs to be done to get these changes to compile with the pgi compiler.

2022-05-20 09:10 UTC, Hallberg-NOAA requested changes
I thought that these changes looked good, but apparently the pgi compiler disagrees. Please make the changes that are needed to get the pgi compiler to work.

2022-05-20 14:19 UTC, marshallward commented
We should be building with PGI `-Mbackslash` but I have replaced `\` with `achar(92)`

2022-05-20 19:08 UTC, Hallberg-NOAA approved these changes

2022-05-20 19:09 UTC, Hallberg-NOAA commented
With the updates, this PR has now passed the pipeline testing at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/15555.

2022-05-20 19:09 UTC, merged