+Add option to fix z-file layer initialization bug
NOAA-GFDL/MOM6 pull request #1266
Opened 2020-12-02 02:13 UTC by Hallberg-NOAA

Added a new runtime flag, LAYER_Z_INIT_IC_EXTRAP_BUG, to allow for the
correction of a vertical indexing bug when initializing a layer-mode
configuration from a Z-space temperature and salinity file with nominally
unstable density profiles in the bottommost points in the z-space file.  Also
corrected some spelling errors in MOM_state_initialization.F90.  By default, all
solutions are bitwise identical, but there is a new entry in some
MOM_parameter_doc files.

2020-12-04 17:33 UTC, adcroft approved these changes

2020-12-04 17:40 UTC, adcroft commented
I assume this would have affected CM2G63L initial conditions? Might explain that initial bottom warming Toni asked us about...

2020-12-04 17:42 UTC, adcroft requested changes
Conflict needs resolving as a result of ice_shelf PR.

2020-12-10 22:52 UTC, marshallward approved these changes

2020-12-10 22:53 UTC, adcroft approved these changes

2020-12-11 03:12 UTC, marshallward commented
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/11655

2020-12-11 04:30 UTC, merged