Update flux const
NOAA-GFDL/MOM6 pull request #1427
Opened 2021-06-15 20:52 UTC by wfcooke

Updating for addition of FLUX_CONST_SALT and FLUX_CONST_TEMP with clean history.
Unit_scaling has been added, but answers change for different values of T_RESCALE_POWER.

2021-06-17 20:50 UTC, Hallberg-NOAA requested changes
This PR is failling with "invalid memory references" in the OM4_025 test case with the gnu compiler in the pipeline tests.  Unfortunately the trace-back for these errors does not provide concrete information about where in the code the error is occurring (see
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/jobs/65471 ), but if I had to guess, the conditional allocation of fluxes%salt_flux_added and fluxes%heat_flux_added would seem like the most likely suspect.  Running with the intel compiler or with with an executable compiled for debugging might give more useful information.

  Please correct these errors and verify that the OM4_025 test case runs properly with the updated code.

2021-06-18 00:47 UTC, MJHarrison-GFDL commented
Thanks @Hallberg-NOAA . @wfcooke , can you please remore my changes for the conditional allocation of these arrays, Sorry about the mixup.

2021-06-24 09:38 UTC, Hallberg-NOAA commented
After the update, this PR is now passing the pipeline testing at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/12946, but because it changes the contents of the MOM_parameter_doc files, it has to be merged manually.

2021-06-24 09:38 UTC, Hallberg-NOAA approved these changes

2021-06-24 14:37 UTC, merged