Horizontal Regridding MOM_IO
NOAA-GFDL/MOM6 pull request #1451
Opened 2021-07-22 11:53 UTC by MJHarrison-GFDL

This removes netCDF API calls contained in MOM_horizontal_regridding and replaces with calls to MOM_io routines.

2021-07-22 14:05 UTC, Hallberg-NOAA requested changes
At first glance, these changes mostly look good to me. However, any changes to the interfaces in config_src/infra/FMS1 also have to be mirrored in the corresponding interface in config_src/infra/FMS2.

2021-07-27 15:01 UTC, Hallberg-NOAA approved these changes

2021-07-30 13:37 UTC, Hallberg-NOAA commented on config_src/infra/FMS2/MOM_io_infra.F90
> +!> Extracts and returns the axis data stored in an axistype.
This does not seem like the right description for the subroutine `set_axis_data()`.  Rather it seems to have been copied unmodified from `get_axis_data()`.  Please correct this desciption.

2021-07-30 14:00 UTC, Hallberg-NOAA commented on config_src/infra/FMS2/MOM_interp_infra.F90
> -public :: get_external_field_info, axistype, get_axis_data
These changes in the publicly declared interfaces from the FMS2/MOM_interp_infra module do not appear to mirror changes in the FMS1/MOM_interp_infra module.  They need to be kept identical.

2021-07-30 14:01 UTC, Hallberg-NOAA requested changes
The additional changes appear to be moving in the right direction, but the new comments describing set_axis_data need to be corrected.  Also, there are changes to the interfaces that are declared to be public from config_src/infra/FMS2/MOM_interp_infra that do not appear to be in line with what is done for FMS1/MOM_interp_infra.  Please correct these issues before this PR is merged into dev/gfdl.

2021-08-05 14:16 UTC, marshallward commented
I find it confusing that there is a generic `set_axis_data()` function available to both frameworks, yet only one of them can actually use the function.

Since this function appears to only be accessed inside of the framework, I feel it would be better to make this an internal (possibly private) function exclusive to FMS2 and not part of the framework API.

2021-08-13 14:46 UTC, MJHarrison-GFDL commented
The reason set_axis_data exists in the fms2 framework is in order to copy the axis data from the mpp_axis type. In the case of FMS1, axistype is identical to mpp_axis, so it is not necessary to copy the data. I personally do not see a problem making this a null operation in one framework.  The point of adding the warning was so that in case anyone tried to call this routine when using FMS1, they would be made aware that the call can be skipped. 

I could make it private by moving to MOM_interp_infra, but it would involve moving the axistype definition and methods and create a dependency in MOM_io_infra on MOM_interp_infra, which seems backwards.

2021-08-18 17:28 UTC, marshallward commented
I know that a different trajectory has been decided for this PR, but wanted to follow up and withdraw my objection to introducing `set_axis_data`.  I had incorrectly though that it was raising an ERROR, not a WARNING.

I have no problem with "no-op" functions like this in one framework if it is (for example) indirectly doing the work in another function.

I would have suggested that you remove the WARNING rather than print it, since stdout is already too noisy.  But given that you're going to rework this PR, it's not necessary.

2021-08-25 14:07 UTC, closed without merging