Fix to dumbbell initialization in layer mode
NOAA-GFDL/MOM6 pull request #160
Opened 2022-07-07 16:44 UTC by WenhaoChen89

This PR fixes the initialization of the dumbbell test to run with the layer mode. 
1. The initial layer thickness is changed to follow the isopycnal
2. The initial salinity is set up using the 'fit' method. 
3. The sponge is added for the layer mode

2022-07-10 11:28 UTC, Hallberg-NOAA commented on src/user/dumbbell_initialization.F90
> +  if(.not. use_ALE) verticalCoordinate = "LAYER"
Please add a space between if and the following parenthesis, as discussed in the MOM6 style guide at https://github.com/NOAA-GFDL/MOM6/wiki/Code-style-guide#white-space.

2022-07-10 11:29 UTC, Hallberg-NOAA commented on src/user/dumbbell_initialization.F90
> +  if(.not. use_ALE) call MOM_error(FATAL,  "dumbbell_initialize_temperature_salinity: "//&
As with line 136, please add a space between if and the following parenthesis, as discussed in the MOM6 style guide at https://github.com/NOAA-GFDL/MOM6/wiki/Code-style-guide#white-space.

2022-07-10 11:31 UTC, Hallberg-NOAA requested changes
Overall this is a useful contribution that is moving in the right direction, but there is a dimensionally incorrect expression (noted in the line-specific comments) that will need to be corrected before this PR can be accept.  As written, this would fail the dimensional consistency testing if Z_RESCALE_POWER is not set equal to H_RESCALE_POWER.

2022-07-11 17:53 UTC, Hallberg-NOAA commented on src/user/dumbbell_initialization.F90
> +        eta(i,j,k) = eta(i,j,k-1)-h_in(i,j,k-1)
This expression calculating the interface heights is dimensionally inconsistent (eta and depth_tot have units of Z, while h_in has units of H). This expression could be compared with the dimensionally correct one at line 175, above.

2022-07-11 17:59 UTC, Hallberg-NOAA reviewed
Some of the issues with this code have now been addressed, but the dimensionally inconsistent expression on line 454 of dumbbell_initialization.F90 still needs to be corrected by multiplying h_in by GV%H_to_Z.  I would also request that after this change is made, that this contribution should be tested for dimensional consistency by running it with various settings for H_RESCALE_POWER and Z_RESCALE_POWER; the answers should be identical for any values between about -140 and 140 for these factors. For completeness of testing these two parameters should NOT use the same value.

2022-07-15 17:15 UTC, Hallberg-NOAA approved these changes

2022-07-15 17:20 UTC, Hallberg-NOAA commented
All of my concerns with this PR have now been addressed, and I see this as a valuable new contribution.

  I am, however, recommending that we handle this PR via a squash merge, as it has a relatively high number of commits (9) for a straightforward new contribution, and several of the commits are partial or full reversions of the earlier commits.

2022-07-18 18:14 UTC, marshallward commented
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/16147 :heavy_check_mark: 

(NOTE: There were multiple errors from the CI, but appear to be network-related and not to do with this PR.)

2022-07-18 18:15 UTC, merged