Document units in 9 vertical param modules
NOAA-GFDL/MOM6 pull request #253
Opened 2022-11-23 13:24 UTC by Hallberg-NOAA

Documented numerous internal variables and their units in 9 vertical parameterization modules (MOM_bkgnd_mixing, MOM_bulk_mixed_layer, MOM_diabatic_aux, MOM_diabatic_driver, MOM_entrain_diffusive, MOM_kappa_shear, MOM_regularize_layers, MOM_set_diffusivity and MOM_set_viscosity). This commit includes the addition of units arguments in 9 unlogged get_param calls.  A number of spelling errors were also corrected in comments.  All answers and output are bitwise identical.

2022-11-28 22:09 UTC, adcroft requested changes
This looks good but I'm uncomfortable about the precedent of four exceptions to the usual pattern when specifying units and scaling of run-time parameters.

The four exceptions are reading hidden diffusivity values, for checking or defaults, and not following the pattern for all other parameters which would normally have `scale=US%m2_s_to_Z2_T` . However, the new code instead (and correctly) sets scale=1 because these parameters are being used in MKS units instead of MOM6 units. In each case it seems a different approach could have avoided using MKS inside the model which would avoid breaking the pattern (which is documentation of how to do things). It would be all too easy (though unlikely) for one of these exceptions to the pattern to used as a template by someone else.

2022-11-29 19:00 UTC, Hallberg-NOAA commented on src/parameterizations/vertical/MOM_bkgnd_mixing.F90
> +                   units="m2 s-1", default=-1., scale=1.0, do_not_log=.true.)
I have modified this code snippet and the other one on line 158 to use the usual scale factor for a variable with these units, and it works just fine.

2022-11-29 19:01 UTC, Hallberg-NOAA commented on src/parameterizations/vertical/MOM_diabatic_driver.F90
> +    call get_param(param_file, mdl, "KD", Kd, units="m2 s-1", default=0.0, scale=1.0)
The code has now been modified exactly as suggested.

2022-11-29 19:01 UTC, Hallberg-NOAA commented on src/parameterizations/vertical/MOM_kappa_shear.F90
> +  call get_param(param_file, mdl, "KD", KD_normal, units="m2 s-1", scale=1.0, default=0.0, do_not_log=.true.)
The code has now been modified exactly as suggested.

2022-11-29 19:38 UTC, adcroft approved these changes
Perfect!  Testing at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/17566

2022-11-29 21:05 UTC, adcroft commented
As expected, the difference
```
< MAX_RINO_IT = 25                !   [nondim] default = 50
---
> MAX_RINO_IT = 25                ! default = 50
```
appeared in following doc files:
coupled_AM2_LM3_SIS2/Intersperse_ice_1deg/MOM_parameter_doc.short coupled_AM2_LM3_SIS2/Intersperse_ice_1deg/MOM_parameter_doc.all coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/MOM_parameter_doc.short coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/MOM_parameter_doc.all coupled_AM2_LM3_SIS2/Concurrent_ice_1deg/MOM_parameter_doc.short coupled_AM2_LM3_SIS2/Concurrent_ice_1deg/MOM_parameter_doc.all ice_ocean_SIS2/SIS2_bergs_cgrid/MOM_parameter_doc.all ice_ocean_SIS2/SIS2_bergs_cgrid/MOM_parameter_doc.short ice_ocean_SIS2/SIS2_cgrid/MOM_parameter_doc.all ice_ocean_SIS2/SIS2_cgrid/MOM_parameter_doc.short ice_ocean_SIS2/Baltic_ALE_z_offline_tracers/MOM_parameter_doc.short ice_ocean_SIS2/Baltic_ALE_z_offline_tracers/MOM_parameter_doc.all ice_ocean_SIS2/OM_1deg/MOM_parameter_doc.all ice_ocean_SIS2/OM_1deg/MOM_parameter_doc.short ice_ocean_SIS2/Baltic/MOM_parameter_doc.all ice_ocean_SIS2/Baltic/MOM_parameter_doc.short ice_ocean_SIS2/OM4_025/MOM_parameter_doc.all ice_ocean_SIS2/OM4_025/MOM_parameter_doc.short ice_ocean_SIS2/Baltic_OM4_05/MOM_parameter_doc.short ice_ocean_SIS2/Baltic_OM4_05/MOM_parameter_doc.all ice_ocean_SIS2/OM4_05/MOM_parameter_doc.short ice_ocean_SIS2/OM4_05/MOM_parameter_doc.all ice_ocean_SIS2/SIS2/MOM_parameter_doc.all ice_ocean_SIS2/SIS2/MOM_parameter_doc.short ice_ocean_SIS2/Baltic_OM4_025/MOM_parameter_doc.short ice_ocean_SIS2/Baltic_OM4_025/MOM_parameter_doc.all ocean_only/nonBous_global/MOM_parameter_doc.short ocean_only/nonBous_global/MOM_parameter_doc.all ocean_only/DOME/MOM_parameter_doc.all ocean_only/DOME/MOM_parameter_doc.short ocean_only/benchmark/MOM_parameter_doc.all ocean_only/benchmark/MOM_parameter_doc.short ocean_only/global_ALE/z/MOM_parameter_doc.short ocean_only/global_ALE/z/MOM_parameter_doc.all ocean_only/global_ALE/layer/MOM_parameter_doc.short ocean_only/global_ALE/layer/MOM_parameter_doc.all ocean_only/global_ALE/hycom/MOM_parameter_doc.all ocean_only/global_ALE/hycom/MOM_parameter_doc.short ocean_only/single_column/KPP/MOM_parameter_doc.all ocean_only/single_column/KPP/MOM_parameter_doc.short ocean_only/single_column/BML/MOM_parameter_doc.short ocean_only/single_column/BML/MOM_parameter_doc.all ocean_only/single_column/EPBL/MOM_parameter_doc.all ocean_only/single_column/EPBL/MOM_parameter_doc.short ocean_only/circle_obcs/MOM_parameter_doc.all ocean_only/circle_obcs/MOM_parameter_doc.short

2022-11-29 21:05 UTC, merged