makedep: Include object file dependencies
NOAA-GFDL/MOM6 pull request #288
Opened 2022-12-20 17:09 UTC by marshallward

The current implementation of makedep contains something like a race condition, where the creation of the .mod and .o files may be in an order which breaks the current dependency tree.  Currently, .mod depends on .o, and changes to a module do not trigger rebuilds of dependent source.

Rather than try to sort out the rule order, which could even depend on compiler internals, this patch just adds both object and module output files as dependencies, and rebuilds if either changes.

We might want to come back to this someday and understand the actual order of rule execution.

Thanks to Alistair Adcroft (@adcroft) for proposing this solution.

2022-12-21 18:54 UTC, adcroft requested changes
I agree with the change to the normal makefile output, but when debugging is turned on (`makedep -d ...`) I think it better to report both `found_mods` and `found_deps`. Could you add that debugging?

2022-12-21 18:57 UTC, marshallward commented
`found_mods` and `found_objs`?  or do you also want `found_deps`?

2022-12-21 19:00 UTC, adcroft commented
I thought `found_obs` would be very long but I see not, so maybe that too? I just want to make sure there's enough information to understand what led to the local rule.

2022-12-21 19:05 UTC, marshallward commented
I just did `found_mods` and `found_objs` since `found_deps` is just the combination of the two

2022-12-22 16:44 UTC, marshallward commented
Not quite on-topic, but I noticed that Cray module files are in ALL CAPS (`MOM.mod`) so perhaps including the `.o` files is essential, just to preserve some overall functionality of the Makefile.

2022-12-22 19:04 UTC, adcroft approved these changes
Looks good.

2022-12-30 17:18 UTC, Hallberg-NOAA commented
This PR has passed pipeline testing at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/17825.

2022-12-30 17:18 UTC, merged