+*Use actual density for internal tide bottom drag
NOAA-GFDL/MOM6 pull request #415
Opened 2023-07-20 19:16 UTC by Hallberg-NOAA

This PR consists of a set of commits that calculates the actual density averaged over a near-bottom region when in non-Boussinesq mode via the new subroutine find_rho_bottom, and then uses this calculate the bottom drag experienced by the internal tides.  As a part of this, there are new arguments to propagate_int_tide, itidal_lowmode_loss and find_N2_bottom, and changes to the units of a handful of internal variables, as well as a new array in the transparent int_tide_input_type.

 All answers are bitwise identical in Boussinesq mode, but some solutions will change in non-Boussinesq mode with this change, and there are new arguments to publicly visible subroutines and a new element in a transparent type.

  The commits in this PR include:

- NOAA-GFDL/MOM6@c0e9b26b6 +*Non-Boussinesq internal tide drag uses density
- NOAA-GFDL/MOM6@e62a930c6 +Add find_rho_bottom

2023-07-28 13:32 UTC, raphaeldussin requested changes
All units check out.

2023-07-28 13:32 UTC, raphaeldussin commented on src/parameterizations/lateral/MOM_internal_tides.F90
> +    if (GV%Boussinesq .or. GV%semi_Boussinesq) then
:+1 on units

2023-07-28 13:32 UTC, raphaeldussin commented on src/core/MOM_interface_heights.F90
> +          if (dz(i,k) > 0.0) then
should it be `dz(i,k) - dz_bbl_rem(i) > 0` to catch any partial layer?

2023-07-28 17:08 UTC, raphaeldussin approved these changes

2023-07-31 19:59 UTC, marshallward approved these changes
Approving on behalf of @raphaeldussin

2023-07-31 21:12 UTC, marshallward commented
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/20090 :heavy_check_mark:

2023-07-31 21:12 UTC, merged