Refactoring density integrals for efficiency
NOAA-GFDL/MOM6 pull request #591
Opened 2024-03-31 17:50 UTC by Hallberg-NOAA

Refactored 4 routines (`int_density_generic_pcm()`, `int_density_generic_ppm()`, `int_spec_vol_generic_pcm()` and `int_spec_vol_generic_plm()`) in density integrals for greater computational efficiency by doing fewer calls to the equation of state routines but calculating entire rows of densities at subgrid locations with each each call, replicating what was already being done `int_density_dz_generic_plm()`. To accomplish this, a number of variables now use larger arrays than previously.  The total computational cost of the non-Boussinesq pressure gradient force calculation was more than 50% greater with the previous code in some tests.  All answers are bitwise identical.

2024-04-15 14:55 UTC, marshallward commented
I would guess that you should see equivalent performance in a 2D arrays like `T_N(1:N,iscB+c1:isec+c2)` rather than the staggered 5-tuple and 15-tuple 1D arrays introduced here, which is introducing a lot of complexity.  Although the 2D array is not required to be contiguous, there is hardly a compiler in the world where this is not true.  (If needed, the `contiguous` keyword could be added to `calculate_density`, `calculate_spec_vol` etc, although I would not recommend it).

I am guessing that would require new 2D interfaces for `calculate_density` etc.

There might be further benefit to break out of a single i-loop and do it over the full i-/j- arrays, although that would also require 3D interfaces.

2024-04-24 19:44 UTC, marshallward requested changes
While refactoring this PR, I found a few issues in the dz PCM integral, and another likely issue in the dz PPM when the Stanley EOS is enabled.  These would not be detected by our current testing, since AFAIK our layered tests use analytic EOS integration rather than PCM quadrature.

These were detected in the `benchmark` test with `EOS_QUADRATURE` turned on.

Although my changes are complete, we will apply my changes on top of this PR, rather than rewriting this one.

2024-04-24 19:44 UTC, marshallward commented on src/core/MOM_density_integrals.F90
> +          p15(pos+n) = p15(pos+n-1) + GxRho*0.25*dz
`dz` should be `dz_x(m,i)`

2024-04-24 19:44 UTC, marshallward commented on src/core/MOM_density_integrals.F90
> +          intz(m) = G_e*dz_x(m,i)*( C1_90*( 7.0*(r15(pos+1)+r15(pos+5)) + &
This loop is missing a `pos = i*15 + (m-2)*5`

2024-04-24 19:44 UTC, marshallward commented on src/core/MOM_density_integrals.F90
> +          p15(pos+n) = p15(pos+n-1) + GxRho*0.25*dz
This `dz` should be `dz_y(m,i)`

2024-04-24 19:44 UTC, marshallward commented on src/core/MOM_density_integrals.F90
> +        if (use_varT) T25(I*5+1:I*5+n) = tv%varT(i,j,k)
I believe these `I*5+1:I*5+n` loops should be `I*5+1:I*5+5`, but I haven't run any Stanley EOS tests.

2024-04-26 08:57 UTC, Hallberg-NOAA commented
Thank you for spotting these bugs. I have updated this commit to address the 4 bugs noted above, plus two others that I found after expanding my testing to set EOS_QUADRATURE = True.

2024-04-27 15:02 UTC, marshallward commented
Could you document the other two changes that were needed here?  I will need to confirm that they were fixed in my changes.

2024-04-27 18:17 UTC, Hallberg-NOAA commented
The other two bugs in the original pull request were an incorrect memory declaration for `S5` in `int_spec_vol_dp_generic_pcm()` and a missing `pos = ` assignment in `int_density_dz_generic_ppm()`.  Both bugs would have been eliminated in the much simpler refactoring of this module that you are doing.

2024-04-29 23:07 UTC, marshallward commented
I have profiled these changes and they show a very clear speedup.  Results for a 6hr run of `benchmark` using the legacy ("buggy") Wright EOS with `EOS_QUADRATURE` enabled.

The current code:
```
(Ocean pressure force)                  24     15.356693
(Ocean pressure force)                  24     15.422615
(Ocean pressure force)                  24     15.515217
```
This PR:
```
(Ocean pressure force)                  24      6.039421
(Ocean pressure force)                  24      6.056434
(Ocean pressure force)                  24      6.034422
```
This 2.5x speedup is very reproducible.

The suggested refactor is currently unable to achieve this level of performance.  The conversion from a 1D to 3D array appears to introduce a slowdown from 6s to about 8s, and appears to be due to converting the 15N loop to nested 3x5xN element loops.  The compilers are either unable or unwilling to convert these to single loops.  (The `contiguous` keyword was no help here.)

@adcroft and I have tested a potential version using assumed-size arrays which appear to get very close to the optimized speed (0.13/6.03 sec ~ 2%)
```
(Ocean pressure force)                  24      6.221991
(Ocean pressure force)                  24      6.187612
(Ocean pressure force)                  24      6.166069
```
and believe there may be additional speedups using this technique.

Since there are no plans to replace this commit, I will approve this one and will continue to develop the improvements to the EOS, which will be submitted into a separate PR.

2024-04-30 03:15 UTC, marshallward commented
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/23267 :heavy_check_mark:

2024-04-30 03:15 UTC, merged

2024-04-30 03:43 UTC, marshallward commented
The previous runtimes only contained updates to 3d array times (which dominated the profile).  After updating the 2d profiles, the runtimes are equivalent.

The accepted PR using packed 1D arrays:
```
(Ocean pressure force)                  24      5.995598
(Ocean pressure force)                  24      6.019213
(Ocean pressure force)                  24      5.997528
```

Proposed changes based on 2d/3d arrays (not yet submitted):
```
(Ocean pressure force)                  24      5.955973
(Ocean pressure force)                  24      5.997446
(Ocean pressure force)                  24      5.985435
```
So there is no longer any reason to not refactor this PR to replace the pack arrays with equivalent 2D and 3D arrays.

2024-05-01 04:14 UTC, marshallward commented
I would not normally keep bantering on in a merged PR, but this PR appears to have changed answers, at least in `benchmark` using the Wright EOS and `EOS_QUADRATURE = True`.
```
4c4
<     24,       0.250,     0, En 5.4681542507953240E-01, CFL  0.01994, SL -1.1407E-08, M 7.90973E+19, S 35.0000, T  5.0639, Me  1.93E-16, Se  6.51E-15, Te  3.38E-15
---
>     24,       0.250,     0, En 5.4681542498895175E-01, CFL  0.01994, SL -1.1405E-08, M 7.90973E+19, S 35.0000, T  5.0639, Me  1.95E-16, Se  6.65E-15, Te  3.39E-15
```
I used ifort (IFORT) 2021.7.1 20221019 with -O2 optimization (plus essential flags).

I am not sure if this requires special action.  I am unsure if anyone is even using EOS_QUADRATURE in production.  I first noticed it because my refactoring of this PR produced a third set of answers (equally small in size).

2024-05-01 18:51 UTC, marshallward commented
I repeated using all of the GFDL flags:
* `-O2`
* `-fp-model source`
* `-march=core-avx-i`
* `-qno-opt-dynamic-align`
and the answers now agree (and in many cases are faster, although that is somewhat expected).

I would have thought that `-fprotect-parens` was sufficient for bit reproducibility, but there appears to be more going on here.  But that is a conversation for another place and time.