Better error messages in interpolate_for_nondim_position
NOAA-GFDL/MOM6 pull request #657
Opened 2024-05-29 14:33 UTC by Hallberg-NOAA

Cleaned up the error messages when there are fatal problems in `interpolate_for_nondim_position()` in the MOM_neutral_diffusion module to explicitly give an indications of all the problems.  These had previously triggered fatal errors (or should have), but had less explicit or incorrect error messages in some cases, so all solutions and behavior are identical in any cases that worked previously.

2024-06-24 20:51 UTC, marshallward requested changes
I believe that the conditionals can be simplified due to the boundedness of `interpolate_for_nondim_position`, and the error message can be consolidated into a single block.

While this does not need to be addressed now, we should explore if this function might be written without branching, and without `MOM_error` calls.  Both coule be making vectorization and GPU migration more difficult.

2024-07-03 15:15 UTC, Hallberg-NOAA commented on src/tracer/MOM_neutral_diffusion.F90
> +       (interpolate_for_nondim_position < 0.) .or. (interpolate_for_nondim_position > 1.) ) then
These are all good questions.  Probably the right person to answer them would be @ashao, who wrote the original version of this code.

  I agree with your analysis of how the logic could be simplified.  Everything in this commit is retaining the original logic, but just making the messages more explicit.  I would be happy to modify this as suggested, but before doing so, I would prefer to hear what @ashao thought about this.

2024-07-11 19:51 UTC, Hallberg-NOAA commented
This PR has been revised as suggested.

2024-07-11 21:17 UTC, marshallward approved these changes

2024-07-11 22:12 UTC, marshallward commented
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/mom6ci/MOM6/-/pipelines/24069 :heavy_check_mark:

2024-07-13 09:55 UTC, merged