*+Add ePBL bottom boundary layer mixing option
NOAA-GFDL/MOM6 pull request #717
Opened 2024-09-04 22:31 UTC by Hallberg-NOAA

This series of two commits adds the option to do energetically consistent bottom boundary layer mixing with
the new routine `ePBL_BBL_column()`.  `ePBL_BBL_column()` is closely based on the surface-focused ePBL mixing in `ePBL_column()`, but without adding convective instability driven mixing or mean-TKE driven mixing to avoid possible
double-counting.  This new option is enabled by setting the new runtime parameter EPBL_BBL_EFFIC to be positive.  The changes that actually adds ePBL_BBL_column is in the second of the two commits.

  The first commit corrects a single-line bug that causes `ePBL_column()` to set the wrong variable and then use an uninitialized variable when `EPBL_ORIGINAL_PE_CALC` is set to false.  This bug was present when the `EPBL_ORIGINAL_PE_CALC` was first added on Sept. 30, 2016, but it was not detected because only the default case with `EPBL_ORIGINAL_PE_CALC = True` appears to being used or tested.  Any runs that used this code with debugging compile options would have trapped it immediately.  This will change answers when `EPBL_ORIGINAL_PE_CALC` is false.

  If both `EPBL_BBL_EFFIC` and `BBL_EFFIC` are set to positive values, there is a risk of double-counting, but this case is not being trapped for now.

  Within `ePBL_column()`, the `hp_a` variable was converted from a scalar into a 1-d array to emphasize where these variables are located and to bring `ePBL_column()` closer to what would be required if the new diffusivities were being applied on top of diffusivities from other processes, as is the case in `ePBL_BBL_column()`.   Several comments in `find_PE_change()` and `ePBL_column()` were corrected.  Two allocatable three-dimensional diagnostic arrays that had been in the `energetic_PBL` control structure were converted into local arrays to reduce the dedicated memory requirements when these diagnostics are enabled.

  The changes include the addition of a new mandatory `vertvisc_type` argument to the publicly visible routine `energetic_PBL()`.

  When this new ePBL bottom boundary layer mixing option is enabled, there are several new diagnostics available that are related to bottom boundary layer mixing.  Several new checksum calls were also added with this new option when `DEBUG = True`. The MOM_parameter_doc files are altered by the addition of two new runtime parameters, and by the correction of several spelling errors in the descriptions of other ePBL parameters.  By default, all answers are bitwise identical.

  This commits in this PR include:

- NOAA-GFDL/MOM6@3034aed0b +(*)Add ePBL bottom boundary mixing option
- NOAA-GFDL/MOM6@8a2a7c99f *Fix a bug when EPBL_ORIGINAL_PE_CALC is false

2024-10-01 17:09 UTC, Hallberg-NOAA commented
I am converting this to a draft PR , because while I believe that it is correct (and worth assessing), I think that it could be made much more efficient. We are not using released mean kinetic energy to drive added bottom boundary layer mixing, which means that we can solve directly for the diffusivity that can be supported by a given energy increment without having to do so iteratively with Newton's method.

2024-11-23 15:46 UTC, Hallberg-NOAA commented
This PR has now been revised into its complete form, and ready for review.  Please do not squash this PR, as each of the 5 commits that comprise this PR are significant, either in their scope or by fixing a bug.

2024-12-02 13:54 UTC, adcroft submitted a review, later dismissed
Looks good to me. Wondering is @breichl should also look at this?

2024-12-02 22:53 UTC, Hallberg-NOAA commented
This PR has been updated with one final commit to allow for the bottom boundary layer parameters to be specified separately from the surface boundary layer parameters, and to adjust the energetics of the bottom boundary layer mixing to account for the exponential decay of the bottom-driven TKE away from the bottom.

2024-12-11 17:42 UTC, breichl approved these changes
This is a well needed addition to MOM6-ePBL for having the BBL parameterization consistent with the OSBL.  We should consider building off of this to enable m* functionality as another option for setting the energetics of the BBL mixing.  However, I think this PR should be merged and tested as-is, and consideration of other parameterizations for the mixing energy can be added to this in the future.

I noted one very minor caps-lock typo, but did not spot any obvious necessary changes.

2024-12-11 23:40 UTC, adcroft requested changes
When you change MAX -> max, if you rebase at the same time it will save time when pushing this through the pipeline

2024-12-11 23:42 UTC, adcroft commented
PS> Feel free to push the revised pr/717 to the pipeline overnight (at 4am?) so I can just click some buttons in the morning.

2024-12-12 09:26 UTC, Hallberg-NOAA commented on src/parameterizations/vertical/MOM_energetic_PBL.F90
> +            mixlen_BBL(K) = MAX(CS%min_BBL_mix_len, ((dz_tt*hbs_here)*vstar) / &
Thanks for spotting this; it has now been fixed.

  This uppercase MAX actually came from copying a block of code from another part of this file that had been there for over 5 years, but I have now fixed the MAX in both places.

2024-12-12 09:29 UTC, Hallberg-NOAA commented
The pipeline testing was just triggered for this PR.  (Sorry, but this was 29 minutes later than you had requested it.)

2024-12-12 14:29 UTC, adcroft approved these changes

2024-12-12 14:30 UTC, merged