Streaming Filter
NOAA-GFDL/MOM6 pull request #772
Opened 2024-12-10 13:11 UTC by c2xu

The filters and their target frequencies are no longer hard-coded. Instead, multiple filters with tidal or arbitrary frequencies as their target frequencies can be turned on. The filter names are specified in MOM_input and must consist of two letters/numbers. If the name of a filter is the same as the name of a tidal constituent, then the corresponding tidal frequency will be used as its target frequency. Otherwise, the user must specify the target frequency. In either case, the target frequency is specified by "TIDE_${FILTER_NAME}_FREQ".

The restarting capability has also been implemented. Because the filtering is a point-wise operation, all variables are considered as fields, even if they are velocity components.

2024-12-10 13:51 UTC, c2xu commented
Also, while working on this PR, I encountered an issue (#773) related to creating restart files, which seems to be a bug to me.

2025-01-19 22:24 UTC, Hallberg-NOAA commented
I have examined the code in this PR, and overall it looks sensible.  However, I do not see where the filtered velocities are being used, either to change the model state or as output.  Is this the first of several steps to implement and use the filters, or is there something that I am missing about this PR?

2025-01-19 22:36 UTC, c2xu commented
> I have examined the code in this PR, and overall it looks sensible. However, I do not see where the filtered velocities are being used, either to change the model state or as output. Is this the first of several steps to implement and use the filters, or is there something that I am missing about this PR?

Yes, another PR of frequency-dependent internal wave drag will follow once this is approved and merged. However, I think there is a potential problem with defining the additional dimensions in the restarting files (#773). It would be great if you could take a look at it, @Hallberg-NOAA. I also want to add the restarting capability to the harmonic analysis module, but it might be a good idea to do so after this issue is fixed.

2025-01-20 10:28 UTC, Hallberg-NOAA commented on src/parameterizations/lateral/MOM_streaming_filter.F90
> +  real, allocatable, dimension(:,:,:)  :: s1, &        !< Dummy variable [A]
If possible, I think that there could be a slightly more explicit description of `s1` here than just a dummy variable, even though that is exactly how it is described in Chu and Zaron (2024).  Perhaps this could be described as "approximately the imaginary complement in time of the part of the signal that is oscillating at the target frequency"?  Similarly, could u1 be described more explicitly as "The filtered part of the data, which is approximately the part that of the signal that is oscillating at the target frequency"?  I know that the interested reader can always go and read Chu and Zaron for the full details, but a few more more words here might be very helpful.

2025-01-20 10:47 UTC, Hallberg-NOAA commented on src/parameterizations/lateral/MOM_streaming_filter.F90
>    dt = now - CS%old_time
When dt = 0, nothing happens in the rest of this routine, so it might be more efficient to add a line like
  `if (now <= CS%old_time) return`
at this point in the code.

Also, it should be noted at line 160 that while `CS%old_time` is being initialized here, there is also an implicit initialization of CS%s1 and CS%u1 to 0 by retaining the values that were set when they were allocated.

2025-01-20 10:52 UTC, Hallberg-NOAA commented on src/parameterizations/lateral/MOM_streaming_filter.F90
> +  allocate(CS%s1(CS%is:CS%ie, CS%js:CS%je, nf)) ; CS%s1(:,:,:) = 0.0
Rather than allocating and initializing arrays in two separate comments, the syntax we now prefer to use in MOM6 is to use the optional `source` argument to `allocate`, so the line 65 would become
`allocate(CS%s1(CS%is:CS%ie, CS%js:CS%je, nf), source=0.0)`
and similarly for line 66.

2025-01-20 10:56 UTC, Hallberg-NOAA commented on src/core/MOM_barotropic.F90
> +  if (CS%use_filter) then
The barotropic solver is called twice, once in the predictor step and once in the corrector step.  For other diagnostics in MOM_barotropic.F90, we use a call to `query_averaging_enabled()` to figure out whether we are in the predictor step or the corrector step, and then we only diagnose what is happening on the predictor step.  To help with any confusion when we are making use of `ufilt` and `vfilt` in future additions of diagnostics or tide-specific parameterizations, I think that it would be very helpful if we were to add a comment here explaining this, such as:
`! Note that the filtered velocities are only updated by filt_accum during the predictor step btstep call.`

2025-01-20 11:07 UTC, Hallberg-NOAA requested changes
Thank you for the explanation of how this PR fits into the broader development of diagnostics of the tidal and de-tided velocities, for example.  Before accepting this, though, I have added a handful of specific suggestions for added comments that I would have found helpful in making sense of the code more quickly and for some minor code changes for efficiency and parsimoniousness. In each case, I leave the decision about whether to accept these suggestions up to you, and I will be happy to accept this PR once you have had a chance to respond to or accept each of the specific suggestions.

For the future changes building on this PR, I think that it would be worthwhile to consider whether it might be more useful to diagnose the tidal velocities at the end of the predictor step call to `btstep()` rather than at the start of the corrector step call.  This would require some additional refactoring, but I think that it would help to line up the filtered velocities and other fields in time with the unfiltered velocities at the time when we usually diagnose them.

2025-01-20 15:53 UTC, c2xu commented
> Thank you for the explanation of how this PR fits into the broader development of diagnostics of the tidal and de-tided velocities, for example. Before accepting this, though, I have added a handful of specific suggestions for added comments that I would have found helpful in making sense of the code more quickly and for some minor code changes for efficiency and parsimoniousness. In each case, I leave the decision about whether to accept these suggestions up to you, and I will be happy to accept this PR once you have had a chance to respond to or accept each of the specific suggestions.
> 
> For the future changes building on this PR, I think that it would be worthwhile to consider whether it might be more useful to diagnose the tidal velocities at the end of the predictor step call to `btstep()` rather than at the start of the corrector step call. This would require some additional refactoring, but I think that it would help to line up the filtered velocities and other fields in time with the unfiltered velocities at the time when we usually diagnose them.

I guess it depends on the application. For de-tiding, placing the `Filt_accum()` call at the end of `btstep()`, and only calling it for the correction step, would be the correct way to do it. For frequency-dependent wave drag, it needs to be called at the beginning of `btstep()`, and for both the prediction and correction step, so that the filtered velocities can be used to calculate the frequency-depending drag later in `btstep()`.

2025-01-20 16:29 UTC, c2xu commented on src/parameterizations/lateral/MOM_streaming_filter.F90
> +  real, allocatable, dimension(:,:,:)  :: s1, &        !< Dummy variable [A]
Thanks. I've added the description to the end of the module.

2025-01-20 17:16 UTC, Hallberg-NOAA commented on src/parameterizations/lateral/MOM_streaming_filter.F90
>    dt = now - CS%old_time
The modifications are a step in the right direction, but because `Filt_accum()` is called for both the predictor step and the corrector step, but only does anything on the former, I think that it is more important for performance for the return to be outside of the test for whether we are initializing `CS%old_time`, and instead return if `now <= CS%old_time` or equivalently if `dt <= 0.0` so that we will quickly return without doing any work if this is the corrector step.

2025-01-20 17:20 UTC, Hallberg-NOAA requested changes
This is getting closer, but I would still consider the condition for the `return` from `Filt_accum()`, as I noted in the updated comment.  Please either `return` if `dt <= 0.0` (or the equivalent) or explain why that is not the right thing to do.

2025-01-20 17:36 UTC, c2xu commented on src/parameterizations/lateral/MOM_streaming_filter.F90
>    dt = now - CS%old_time
Thanks. Now I understand what you mean.

2025-01-20 17:37 UTC, c2xu commented
> This is getting closer, but I would still consider the condition for the `return` from `Filt_accum()`, as I noted in the updated comment. Please either `return` if `dt <= 0.0` (or the equivalent) or explain why that is not the right thing to do.

This has been fixed.

2025-01-20 18:55 UTC, Hallberg-NOAA approved these changes
Thank you very much for this valuable contribution.

2025-01-20 21:39 UTC, Hallberg-NOAA commented
This PR has passed pipeline testing at https://gitlab.gfdl.noaa.gov/ogrp/mom6ci/MOM6/-/pipelines/26127 with the expected changes in entries in the MOM_parameter_doc files.

  There are two parameters (`STREAMING_FILTER_M2` and `STREAMING_FILTER_K1`) that are no longer supported and are not going through the usual year-long obsoleting process.  However because these were only introduced 4 months ago (on Sept. 10, 2024) as prototype code that does not actually alter solutions or lead to any diagnostic output, I am making the judgement call that there is unlikely to be any damage if they are simply dropped.  The new, more general streaming filter is activated with the new runtime parameter `USE_FILTER`, which if selected enables other subsidiary parameters.

2025-01-20 21:39 UTC, merged