+Refactor MOM_opacity to replace hard-coded params
NOAA-GFDL/MOM6 pull request #775
Opened 2024-12-11 14:41 UTC by Hallberg-NOAA

Refactored `MOM_opacity` to replace hard-coded dimensional parameters for the Manizza and Morel opacity fits with run-time parameters.  By default, these parameters are set to the previous hard-coded values, using the recently added defaults argument to `get_param_real_array()`.  The bounds of the frequency band label arrays with the `MANIZZA_05` opacity scheme were also corrected when `PEN_SW_NBANDS > 3`, but it would not by typical to use so many bands for no purpose and these labeling arrays (`optics%min_wavelength_band` and `optics%max_wavelength_band`) do not appear to be used anywhere.  In addition, the unused publicly visible routines `opacity_manizza()` and `opacity_morel()` were eliminated or made private.  All answers are bitwise identical, but there are new entries in some `MOM_parameter_doc` files.

2025-01-08 16:47 UTC, raphaeldussin requested changes
I think there should be a response from the model (e.g. FATAL) to changing parameters that would not have any effect. The rest is nitpicking.

2025-01-08 16:47 UTC, raphaeldussin commented on src/parameterizations/vertical/MOM_opacity.F90
> +        optics%min_wavelength_band(n) = 700. + (n-3)*2100.0*I_NIR_bands
should hardcoded values also be parameters?

2025-01-08 16:47 UTC, raphaeldussin commented on src/parameterizations/vertical/MOM_opacity.F90
>      optics%min_wavelength_band(1) =0
this could be close to 300nm unless we want to include gamma rays and UV

2025-01-12 20:52 UTC, Hallberg-NOAA commented on src/parameterizations/vertical/MOM_opacity.F90
> +              optics%opacity_band(n,i,j,k) = CS%opacity_coef(1,n)
I have modified this PR to fold any non-zero values in `CS%opacity_coef(1,n)` into `CS%opacity_coef(2,n)`, since `a**0 = 1.0`, so the answers will be consistent with what would be obtained if the power had been evaluated.  I have also added a warning if there are non-zero contributions from the ostensibly chlorophyll dependent terms that are actually chlorophyll independent.

2025-01-12 20:53 UTC, Hallberg-NOAA commented on src/parameterizations/vertical/MOM_opacity.F90
>      optics%min_wavelength_band(1) =0
Yes, it could be, but I think that is something we should deal with in a future PR.

2025-01-12 20:53 UTC, Hallberg-NOAA commented on src/parameterizations/vertical/MOM_opacity.F90
> +        optics%min_wavelength_band(n) = 700. + (n-3)*2100.0*I_NIR_bands
Yes, they should, and the PR has now been modified so that they are runtime parameters.

2025-01-13 02:59 UTC, raphaeldussin approved these changes

2025-01-13 14:49 UTC, adcroft commented on src/parameterizations/vertical/MOM_opacity.F90
> -  opacity_manizza = 0.0232 + 0.074*chl_data**0.674
Where did this function go?

2025-01-13 14:56 UTC, raphaeldussin commented on src/parameterizations/vertical/MOM_opacity.F90
> -  opacity_manizza = 0.0232 + 0.074*chl_data**0.674
this looks like an outdated function, also possibly incorrect since the Manizza 2005 scheme is multiband. The opacity is set on line 388 (new code) using a multiband scheme

2025-01-13 15:04 UTC, Hallberg-NOAA commented on src/parameterizations/vertical/MOM_opacity.F90
> -  opacity_manizza = 0.0232 + 0.074*chl_data**0.674
`Opacity_manizza()` was unused, outdated and using hard-coded dimensional constants, so I eliminated it.  I would be OK with restoring it with a new name, like `opacity_manizza_archaic()` as a part of a managed obsoleting process, but I do not see what purpose it serves.

2025-01-13 15:50 UTC, marshallward approved these changes
Approving on behalf of @raphaeldussin but I will let you all decide when the conversation below has been resolved.

2025-01-13 19:57 UTC, Hallberg-NOAA commented
Neither opacity_manizza() nor opacity_morel() appears anywhere in the GFDL ocean-BGC code under version control at https://github.com/NOAA-GFDL/ocean_BGC.  I strongly suspect that these routines are not used anywhere.

2025-01-14 03:28 UTC, Hallberg-NOAA commented
This PR passed pipeline testing at https://gitlab.gfdl.noaa.gov/ogrp/mom6ci/MOM6/-/pipelines/26027, with the expected changes in parameter settings.  However, there are `OPACITY_BAND_WAVELENGTHS` parameters being logged in cases with only a single wavelength band, for which this parameter has little physical meaning, so I have revised this PR to only log `OPACITY_BAND_WAVELENGTHS` when `PEN_SW_NBANDS > 1`.

2025-01-14 13:29 UTC, raphaeldussin approved these changes

2025-01-14 14:57 UTC, merged